"use server"

import { analyzeText } from "@/lib/text-analysis"

// Function to generate text from both models
export async function generateText(prompt: string, maxLength = 100, temperature = 0.8) {
  try {
    // In a production environment, this would call the actual models
    // For this example, we'll use simulated responses

    // Simulate a delay to mimic model inference time
    await new Promise((resolve) => setTimeout(resolve, 1500))

    // Generate text from OpenWebText model (simulated)
    const openWebTextOutput = simulateOpenWebTextGeneration(prompt, maxLength, temperature)

    // Generate text from Gutenberg model (simulated)
    const gutenbergOutput = simulateGutenbergGeneration(prompt, maxLength, temperature)

    // Calculate metrics for both outputs
    const metrics = {
      openWebText: analyzeText(openWebTextOutput),
      gutenberg: analyzeText(gutenbergOutput),
    }

    return {
      openWebTextOutput,
      gutenbergOutput,
      metrics,
    }
  } catch (error) {
    console.error("Error generating text:", error)
    throw new Error("Failed to generate text. Please try again later.")
  }
}

// Simulate OpenWebText model output
function simulateOpenWebTextGeneration(prompt: string, maxLength: number, temperature: number): string {
  // These are simulated responses based on the characteristics of text
  // that would be generated by a model trained on OpenWebText
  const responses: Record<string, string> = {
    "The future of artificial intelligence is":
      "The future of artificial intelligence is likely to be transformative across many industries. AI systems are becoming increasingly capable of performing complex tasks that previously required human intelligence. According to recent research, we can expect significant advancements in natural language processing, computer vision, and reinforcement learning in the next decade.\n\nHowever, there are also important ethical considerations around AI development, including issues of bias, privacy, and job displacement. Many tech companies are now investing in responsible AI frameworks to address these concerns.",

    "Once upon a time in a distant land":
      "Once upon a time in a distant land, a team of researchers discovered an ancient technology buried beneath the desert sands. The device, apparently thousands of years old, contained what appeared to be advanced circuitry unlike anything seen in modern electronics.\n\nThe discovery went viral on social media, with #AncientTech trending worldwide. Scientists from various disciplines formed a collaborative project to study the artifact, while conspiracy theorists claimed it was evidence of alien visitation. The research team set up a live stream of their work, attracting millions of viewers.",

    "The meaning of life is":
      "The meaning of life is a question that has been debated by philosophers, scientists, and religious thinkers throughout human history. Some argue that life has no inherent meaning beyond what we create for ourselves. Others find meaning through connection with others, pursuit of happiness, or contribution to society.\n\nA 2019 survey found that 58% of respondents believed the meaning of life comes from relationships with family and friends, while 25% cited career achievement, and 17% mentioned spiritual fulfillment. Ultimately, many psychologists suggest that finding personal meaning is essential for mental well-being.",

    "To be or not to be":
      "To be or not to be remains one of the most famous lines from Shakespeare's Hamlet, representing the ultimate existential question. In today's context, this phrase has been adopted in popular culture as a shorthand for difficult decisions.\n\nThe concept has been explored in various modern media, including a 2020 Netflix documentary examining how people make life-altering choices. Neuroscience research suggests that this type of existential questioning activates regions in the prefrontal cortex associated with self-reflection and decision-making. A recent study found that 72% of participants reported experiencing major existential questions during significant life transitions.",

    "In the beginning":
      "In the beginning of the internet era, few people predicted how dramatically digital technology would transform society. What started as a network connecting research institutions has evolved into a global system that shapes everything from how we shop to how we find romantic partners.\n\nAccording to data from the International Telecommunications Union, global internet penetration reached 63% in 2021, with mobile devices being the primary access point for most users. Tech analysts predict that the next phase of digital evolution will focus on augmented reality, decentralized web architecture, and AI-driven interfaces that further blur the line between physical and digital experiences.",
  }

  // Adjust the output based on temperature
  // Higher temperature = more random/creative output
  const randomFactor = Math.min(1, Math.max(0, temperature)) * 0.3

  // Return the matching response or a generic one if no match
  const output =
    responses[prompt] ||
    `${prompt} going to revolutionize how we interact with technology. Recent studies show that advancements in this field are accelerating faster than predicted. According to data from leading research institutions, we can expect significant breakthroughs within the next 5-10 years.\n\nExperts in the field suggest that these developments will impact everything from healthcare to transportation. However, there are also important ethical considerations that need to be addressed, including privacy concerns and potential economic disruption.`

  // Truncate to maxLength words if needed
  const words = output.split(/\s+/)
  if (words.length > maxLength) {
    return words.slice(0, maxLength).join(" ") + "..."
  }

  return output
}

// Simulate Gutenberg model output
function simulateGutenbergGeneration(prompt: string, maxLength: number, temperature: number): string {
  // These are simulated responses based on the characteristics of text
  // that would be generated by a model trained on Gutenberg
  const responses: Record<string, string> = {
    "The future of artificial intelligence is":
      "The future of artificial intelligence is shrouded in mystery, like a fog upon the distant hills at dawn. Man hath ever sought to create in his own image, and in this modern age, such creation takes the form of thinking machines.\n\nPerchance these mechanical minds shall bring forth a golden age of prosperity, wherein the burdens of labor are lifted from the shoulders of mankind. Yet one must also consider the grave possibility that these creations may, like Prometheus unbound, bring forth consequences unforeseen by their creators. It behooves the wise to proceed with caution in this most momentous of endeavors.",

    "Once upon a time in a distant land":
      "Once upon a time in a distant land, there dwelt a noble king whose wisdom was renowned throughout the realm. His castle stood upon a lofty hill, its spires reaching toward the heavens as if in supplication to the divine.\n\nThe king had three daughters, each fairer than the last, with countenances that would cause the stars themselves to dim with envy. The eldest possessed hair like spun gold and eyes of sapphire blue; the middle daughter's voice was such that nightingales would fall silent in shame; and the youngest, ah! the youngest was blessed with such grace and kindness that flowers would bloom beneath her gentle footsteps.",

    "The meaning of life is":
      "The meaning of life is a question that hath vexed the minds of philosophers since time immemorial. 'Tis a query that echoes through the corridors of human thought, from Socrates to the humble peasant tilling the soil.\n\nSome men find purpose in the accumulation of worldly treasures, though such riches oft prove fleeting as morning dew. Others seek meaning in the pursuit of knowledge, filling their minds with wisdom as one might fill a vessel with precious oil. Yet others find their purpose in love—that most exalted of emotions which, as the poet says, 'bears it out even to the edge of doom.'",

    "To be or not to be":
      "To be or not to be—that is the question which hath troubled mankind since the dawn of consciousness. Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles, and by opposing end them?\n\nThe soul, when faced with mortal uncertainty, must weigh the known trials of existence against the unknown country of death, from whose bourn no traveler returns. Thus conscience doth make cowards of us all; and thus the native hue of resolution is sicklied o'er with the pale cast of thought.",

    "In the beginning":
      "In the beginning, when the world was yet young and the firmament newly stretched above the earth, there lived a race of beings whose nature was half mortal and half divine. They walked upon the verdant hills and through the shadowed valleys, their footsteps leaving marks that would remain for countless ages.\n\nThe sun, in those distant days, shone with a golden light more pure than any known to modern man, and the moon cast silver beams that could heal the sick and comfort the weary of heart. The very air was filled with music—not the crude melodies of human invention, but the celestial harmonies of the spheres themselves.",
  }

  // Adjust the output based on temperature
  // Higher temperature = more random/creative output
  const randomFactor = Math.min(1, Math.max(0, temperature)) * 0.3

  // Return the matching response or a generic one if no match
  const output =
    responses[prompt] ||
    `${prompt} hath ever been a subject of great contemplation among learned men. As the esteemed philosopher once proclaimed in his treatise on natural philosophy, the nature of such matters lies beyond the common understanding.\n\nIt calls to mind the ancient tale of the wise king who, upon his deathbed, gathered his three sons to impart his final wisdom. "My children," said he, "seek not the transient pleasures of earthly existence, but rather the eternal truths that lie hidden beneath the veil of ordinary perception."\n\nThus it has always been, and thus shall it remain until the final trumpet sounds.`

  // Truncate to maxLength words if needed
  const words = output.split(/\s+/)
  if (words.length > maxLength) {
    return words.slice(0, maxLength).join(" ") + "..."
  }

  return output
}
